---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
        use_backend: dnf4
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

    - name: Add GPG key for the Prometheus repository (Ubuntu)
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Prometheus APT repository (Ubuntu)
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
      when: ansible_distribution == "Ubuntu"

    - name: Install Prometheus (Ubuntu)
      apt:
        name: prometheus
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Enable and start Prometheus service (Ubuntu)
      service:
        name: prometheus
        enabled: yes
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Open port 9090 for Prometheus (Ubuntu)
      ufw:
        rule: allow
        port: 9090
        proto: tcp
        state: enabled
      when: ansible_distribution == "Ubuntu"

    - name: Download Prometheus(CentOS)
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
      when: ansible_distribution == "CentOS"

    - name: Extract Prometheus (CentOS)
      ansible.builtin.shell: tar -zxvf /tmp/prometheus.tar.gz -C /tmp/
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus user (CentOS)
      ansible.builtin.user:
        name: prometheus
        state: present
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus directory (CentOS)
      ansible.builtin.file:
        path: /opt/prometheus
        state: directory
      when: ansible_distribution == "CentOS"

    - name: Set ownership and permissions for Prometheus (CentOS)
      ansible.builtin.file:
        path: /opt/prometheus
        owner: prometheus
        group: prometheus
        mode: '0755'
      when: ansible_distribution == "CentOS"

    - name: Create Prometheus service file (CentOS)
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      when: ansible_distribution == "CentOS"

    - name: Reload systemd (CentOS)
      ansible.builtin.command: systemctl daemon-reload
      when: ansible_distribution == "CentOS"

    - name: Start Prometheus service (CentOS)
      ansible.builtin.service:
        name: prometheus
        enabled: yes
        state: started
      when: ansible_distribution == "CentOS"

    - name: Open Firewall Port for Prometheus (CentOS)
      ansible.builtin.shell: firewall-cmd --add-port=9090/tcp --permanent
      when: ansible_distribution == "CentOS"

    - name: Ensure Firewall Rule Reloaded (CentOS)
      ansible.builtin.shell: firewall-cmd --reload
      when: ansible_distribution == "CentOS"

    - name: Enable Prometheus on system boot (CentOS)
      ansible.builtin.service:
        name: prometheus
        enabled: yes
      when: ansible_distribution == "CentOS"
