---
- name: Install updates (CentOS)
  tags: always
  dnf:
    update_only: yes
    update_cache: yes
    use_backend: dnf4
  when: ansible_distribution == "CentOS"

- name: Install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
